version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: cospace_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cospaceapp123
      POSTGRES_DB: cospace_db
    ports:
      - "5460:5432"
    networks:
      - cospace-network
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cospace_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: cospaceapp123
    networks:
      - cospace-network

networks:
  cospace-network:
    driver: bridge

volumes:
  db-data:
    driver: local
