name: Build and Test Application

on:
  push:
    branches:
      - "feature-14"  # Trigger action on pushes to branch 14
  pull_request:
    branches:
      - "feature-14"  # Trigger action for pull requests targeting branch 14

jobs:
  build:
    runs-on: ubuntu-latest  # You can use 'windows-latest' or 'macos-latest' if needed

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the project and run tests
      - name: Build and test with Gradle
        run: gradle clean build

      # Upload build artifacts (JAR file) as a GitHub Artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar  # This assumes your JAR is created in the `build/libs/` directory
